# A simple action usage
name: Build Kernel spes 4.19 ksun-susfs
on:
  workflow_dispatch:
  push:
    branches:
      - main-ksun-susfs-test

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel spes 4.19 ksun-susfs
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/staciamarchxix/kernel_xiaomi_spes/
          kernel-dir: msm-4.19
          kernel-branch: main
          config: vendor/spes-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu-other: true
          ksu-url: https://github.com/SukiSU-Ultra/SukiSU-Ultra
          aosp-clang-version: r547379
          anykernel3: true
          anykernel3-url: https://github.com/muralivijay/AnyKernel3
          extra-cmd: LLVM=1 LLVM_IAS=1
